--The PADS

SELECT CONCAT(NAME, '(', SUBSTRING(OCCUPATION, 1, 1), ')') AS ModifiedName
FROM OCCUPATIONS
ORDER BY NAME ASC;

SELECT 'There are a total of ' + CAST(COUNT(OCCUPATION) AS VARCHAR) + ' ' + LOWER(OCCUPATION) + 's.' AS OccupationCount
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION ASC;